version: '2'
services:
  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile
    image: new-admin
    container_name: new-admin
    command: npm start
    tty: true
    environment:
      REACT_APP_APIURL: http://localhost:3000
      PORT: 5000
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
    ports:
      - 5000:5000
